Vectorize flags
anki-geo/ultimate-geography pull request #587
Opened 2022-12-16 23:33 UTC by KentGrigo

Issue: https://github.com/anki-geo/ultimate-geography/issues/534
Follow-up on https://github.com/anki-geo/ultimate-geography/pull/577

This PR will vectorize the following flags:

    Belize
    Bolivia
    Costa Rica
    El Salvador
    Peru
    Venezuela

The blurred version of these flags were not vectorized because I wasn't able to blur them properly:

    Bolivia
    El Salvador

This means that the question will be on the rasterized, blurred version of the flag and flip to the vectorized flag.

Note that I've updated many of the flags to correspond to the first flag shown on the countries' Wikipedia pages.

2022-12-17 16:35 UTC, aplaice commented
Thanks for the PR!

Since AFAICT the GitHub diff viewer isn't displaying the changes too conveniently, here are the image changes (old flag and then new):

## Belize :heavy_check_mark: 

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-belize.png)

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-belize.svg)

The proportions have changed, but this is correct.  (The [proportions _should_ be 3:5](https://en.wikipedia.org/wiki/Flag_of_Belize) as i in the new SVG.)

(AFAICT the source file has undergone a flurry of changes in the past couple of years.)

## Bolivia

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-bolivia.png)
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-bolivia.svg)

The blurred image
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-bolivia-blur.png)

This is still the state flag, but with a slightly different coat-of-arms ([old source](https://commons.wikimedia.org/wiki/File:Flag_of_Bolivia_(state).svg) vs. [new source](https://commons.wikimedia.org/wiki/File:Bandera_de_Bolivia_(Estado).svg).).  I'm not quite sure why the state flag linked/displayed on Wikipedia has changed...

I would very strongly prefer the blurred image and the non-blurred one, not to differ (other than blurring), and definitely not significatly, like here.

However, if we were to follow our current guidelines ("first flag") we should switch to the civil flag, so we should resolve #111 first (since the blurring issue might become moot).


## Costa Rica

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-costa_rica.png)
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-costa_rica.svg)

We're removing the coat of arms (switching from state to civil flag).  To avoid back-and-forth we should resolve #111, first.

## El Salvador :white_check_mark: 

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-el_salvador.png)
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-el_salvador.svg)

The blurred image:
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-el_salvador-blur.png)

The blurred and unblurred images now differ slightly (other than in the blur), but this is IMO borderline-OK.

## Peru

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-peru.png)
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-peru.svg)

We're removing the coat of arms (switching from state to civil flag).  To avoid back-and-forth we should resolve #111, first.

## Venezuela

![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/513ae81773951b50d74ac68e34c372c303401aed/src/media/flags/ug-flag-venezuela.png)
![](https://raw.githubusercontent.com/anki-geo/ultimate-geography/d19a01a9e81121ebe1f748c8c27cdc4a046c9086/src/media/flags/ug-flag-venezuela.svg)

We're removing the coat of arms (switching from state to civil flag).  To avoid back-and-forth we should resolve #111, first.


<hr/>

Several issues (as mentioned above):

1. IMO the blurred image should be the same (apart from blurring :)) as the non-blurred image.  (Blocking, but potentially superseded by **2** since we might not need blurring for Bolivia.)
2. We should resolve #111 before switching any more flags to avoid annoying (for users) back-and-forth.  (Technically, we're not releasing soon, so we could change and then change back, but it's easy to forget.)
3. In the long run, the blurred images should also be SVGs, but that can wait.

<hr/>

Sorry for being pedantic!

2022-12-17 17:05 UTC, axelboc commented
For blurring, I could see us being able to add a [`filter`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur) tag to the SVG file and apply the filter conditionally with CSS to the paths/texts that need to be blurred. IMO, it'll be easier to do this as part of the vectorising work than to update the blurred PNGs.

2022-12-17 17:22 UTC, aplaice commented
> For blurring, I could see us being able to add a [filter](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feGaussianBlur) tag to the SVG file and apply the filter conditionally with CSS to the paths/texts that need to be blurred.

That would be convenient, but I don't think we can apply CSS to SVGs that are `img`s (as opposed to SVGs that are inline). (CSS embedded in the SVG files themselves would work, but not CSS in the main Anki template.)

> IMO, it'll be easier to do this as part of the vectorising work than to update the blurred PNGs.

Yes, we definitely shouldn't update the blurred PNGs, but replace them with something derived from the relevant vector images!

2022-12-17 17:25 UTC, axelboc commented
Ah good point, that's a shame 👍

2022-12-17 18:56 UTC, ukanuk commented
From CONTRIBUTING.md:

> The name should be blurred using [Inkscape](https://inkscape.org/)'s Gaussian blur effect as explained in https://github.com/anki-geo/ultimate-geography/pull/247.

2022-12-19 06:30 UTC, KentGrigo commented
Thanks @ukanuk, but I already checked that out. 
Unfortunately, it only states how to apply the filter, not how to make the selection.
However, I've now had the time to look into it and found a solution.

--------

For future reference, here's a guide on how to blur a selection of an SVG file.

To select the part to be blurred
- Use `Edit paths by nodes (N)`
- Click on the text that should be blurred
  - For Bolivia, I also had to select the shadow of the text

To blur
- Select `Filters > Blurs > Blur...`
- Set `Horizontal blur` and `Vertical blur` to `15`
- Un-check `Blur content only`
- Click `Apply`

2022-12-19 06:42 UTC, KentGrigo commented
@aplaice, this should fix 1. and 3.

2022-12-19 11:22 UTC, aplaice approved these changes
Thanks very much! These look great!

I'd still rather we deal with #111 first, but we could, in principle merge and then partially revert.

2023-01-14 17:38 UTC, axelboc requested changes
Nice, thanks! So apart from the minor tweak below, I think the only thing left is to switch back to the [state flag of Costa Rica](https://commons.wikimedia.org/wiki/File:Flag_of_Costa_Rica_(state).svg) (but in SVG of course), as per @aplaice's assessment in https://github.com/anki-geo/ultimate-geography/issues/111#issuecomment-1382229132

2023-01-14 19:08 UTC, KentGrigo commented on CONTRIBUTING.md
> +This field must contain a single HTML image element pointing to the SVG image of a flag - e.g. `<img src="ug-flag-seychelles.svg" />`. The image must be placed in the ` media` folder and named `ug-fl
Nice catch. Thanks.

2023-01-15 12:34 UTC, aplaice approved these changes
AFAICT this looks perfect! LGTM!

2023-01-15 12:35 UTC, KentGrigo commented
I tried to re-request a review from both of you (@aplaice & @axelboc), but it keeps remove the other.
I've now change the flag of Costa Rica back to the state version, but now vectorized.
Also, I added a blurred version as the banner says `Republica de Costa Rica`.

2023-01-15 12:57 UTC, axelboc approved these changes
Awesome, thanks a lot!!

2023-01-15 12:57 UTC, merged

2023-01-15 13:12 UTC, axelboc commented
Summary of changes for future release notes:

- Vectorize the following flags: Belize, Bolivia (+ blurred version), Costa Rica, El Salvador (+ blurred version), Peru, Venezuela
- Add blurred version of flag of Costa Rica
- Use civil flags instead of state flags for Peru and Venezuela
- Update `CONTRIBUTING` to require flag images to be SVG